platform :ios, "8.0"

def pods
  inhibit_all_warnings!
  use_frameworks!

  pod 'SAMKeychain'
  pod 'MD5Digest'

  pod 'SDWebImage'
  pod 'MBProgressHUD'
  pod 'CameraSDK', :path => '~/Work/908/CameraSDK/CameraSDK'
end

target 'StoriesDemo' do
  pods
end
